language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
env:
  - MONGOID_VERSION=2.4
  - MONGOID_VERSION=3.0
matrix:
  exclude:
    - rvm: 1.8.7
      env: MONGOID_VERSION=3.0
    - rvm: 1.9.2
      env: MONGOID_VERSION=3.0
    - rvm: jruby-18mode
      env: MONGOID_VERSION=3.0
